### ISSUE TITLE
Deleting a job sends a GET request

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#100]
I don't believe deleting a job should send a `GET` request as we are changing the state of the server. Also, some browsers will call `GET` requests just by hovering your mouse over a link and not clicking it.

**Comment by brianmcmichael** [comment]
DELETE requests can only be performed via ajax. This will take a little more work than just changing the route.

**Comment by brianmcmichael** [comment]
Fixed by https://github.com/OSC/ood-activejobs/commit/4364af866d2277e57b9271cf2c681fff4bba6480
