### ISSUE TITLE
Deleting job sends weird parameters

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#101]
When I delete a job it sends the following request:

![image](https://cloud.githubusercontent.com/assets/4260509/24804495/9e4e41ec-1b7c-11e7-90a5-e7b9b50f59f1.png)

Note that the `host` is weird.

This fails to delete a job:

![image](https://cloud.githubusercontent.com/assets/4260509/24804524/b39756ba-1b7c-11e7-8dcf-9710831cd19f.png)

**Comment by brianmcmichael** [comment]
This was introduced by the upgrade to `ood_core`. I should be able to troubleshoot this on our system.

**Comment by brianmcmichael** [comment]
Fixed by https://github.com/OSC/ood-activejobs/commit/3e87bdcf9e161905f5fc4f5a9c2b47c195b5332b
