### ISSUE TITLE
Should space exist between icon and "Open File..."

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#102]
Should there be a whitespace here:

![image](https://cloud.githubusercontent.com/assets/4260509/24806547/310fd300-1b83-11e7-8833-0b8af7b562e2.png)

**Comment by brianmcmichael** [comment]
There already is:
https://github.com/OSC/ood-activejobs/blob/master/app/assets/javascripts/application.js.erb#L257
