### ISSUE TITLE
Missing icon for Terminal button?

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#103]
Should there be an icon here:

![image](https://cloud.githubusercontent.com/assets/4260509/24806580/4a22f836-1b83-11e7-81aa-c83c152b6f89.png)

**Comment by brianmcmichael** [comment]
Not sure why it's not appearing. Should be using `glyphicon-console`
https://github.com/OSC/ood-activejobs/blob/master/app/assets/javascripts/application.js.erb#L265

**Comment by nickjer** [comment]
Forgot to mention: This is occurs for the `ood_core` branch.

**Comment by brianmcmichael** [comment]
This is bizarre. Other glyphicons work in it's place. This only seems to affect `glyphicon-console`, the only thing that I could see that could be possibly affecting this is an update to `sass 3.4.23` gem.

We've had ongoing problems with `bootstrap-sass` not playing well with `sass` versions. I'll see if I can find the correct incantation to get this working again.

**Comment by brianmcmichael** [comment]
Resolved by switching to Font Awesome at https://github.com/OSC/ood-activejobs/commit/b4408c3df4be53fc475c0ae47367c22a809b5ef3

**Comment by brianmcmichael** [comment]
Resolved at https://github.com/OSC/ood-activejobs/commit/b4408c3df4be53fc475c0ae47367c22a809b5ef3
