### ISSUE TITLE
Should we advertise OSC in apps?

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#104]
This appears in the footer of the Active Jobs app:

![image](https://cloud.githubusercontent.com/assets/4260509/24829699/fc09c0b8-1c44-11e7-84e8-4cf387f83ef5.png)

So this will appear at every Open OnDemand installation. Is this ok or do we need to change?

@basilgohar and/or @ericfranz?

**Comment by brianmcmichael** [comment]
This was done at https://github.com/OSC/ood-activejobs/commit/f75c10cd6ca368cd3ce5f2298ad5e7afc8f24c17
