### ISSUE TITLE
Show resource manager specific fields in job details view

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-activejobs#107]
Discussed offline.

Instead of normalizing the native attributes to fixed fields (Queue, Walltime, etc.) we want to vary the attributes we normalize to based on the resource manager we are using.

To do this, we need:

1. a simpler view for details
2. a data structure for this normalized data that allows the list of attributes we display, along with the attribute titles, to vary

Some ideas.

1. Get rid of attribute groups "Job Information", "Resources requested", etc. Use a table with small font and list all the attributes. Optionally display 2 columns of tables if we want the list of attributes we are showing to take up available space
2. Have one or more "paths" attributes with the "Open in File Manager" and "Open in Terminal" buttons at the end of each path attribute row
3. Have "Submit args" (which may be a Torque specific attribute available) be a "caption" that is added to the panel header using `<br><small class="text-muted>{{text}}</small>` i.e.
   * ![screen shot 2017-04-12 at 3 55 13 pm](https://cloud.githubusercontent.com/assets/512333/24977143/1ae79fe8-1f9a-11e7-9891-5b405228f33f.png)
   * this caption could be "nil" in that case we just wouldn't display one (so if there isn't anything useful to display right below the id we don't

A very rough idea of a type of normalized data structure:

```ruby
Attribute = Struct.new(:name, :value)


def extended_data_torque(info)
  attrs = []
  attrs << Attribute.new "Username", info.user
  attrs << Attribute.new "Account Name", info.account
  attrs << Attribute.new "PPN", (info.native[:Resource_List] && info.native[:Resource_List][:nodes].to_s.split("ppn=").second) || ''

  paths = []
  paths << Attribute.new "Output Path", info.native[:Output_Path].to_s.split(":").second || info.native[:Output_Path]
  
  submit_args = "Submit Args: " + (info.native[:submit_args].presence || "Not Available")

  { attrs: attrs, paths: paths, caption: submit_args}
end
```

Then when building the view, instead of setting values to fixed hardcoded attributes (like the attributes currently defined on Jobstatusdata: https://github.com/OSC/ood-activejobs/blob/8ac7818017f1a887e50fb5c786bdd1a301d46f50/app/models/jobstatusdata.rb#L10)  we iterate over the list of attributes available

This would address https://github.com/OSC/ood-activejobs/issues/98

**Comment by nickjer** [comment]
How do you handle paths that are files and not directories for the "Open in File Manager" and "Open in Terminal"? I ask because...

```ruby
paths << Attribute.new "Output Path", info.native[:Output_Path].to_s.split(":").second || info.native[:Output_Path]
```

will return a file I believe.

**Comment by brianmcmichael** [comment]
Separate attributes

```
 output_pathname = Pathname.new(self.output_path).dirname
 self.terminal_path = OodAppkit.shell.url(path: (output_pathname.writable? ? output_pathname : ENV["HOME"])).to_s
 self.fs_path = OodAppkit.files.url(path: (output_pathname.writable? ? output_pathname : ENV["HOME"])).to_s
```

**Comment by ericfranz** [comment]
```ruby
Attribute = Struct.new(:name, :value)
Path = Struct.new(:name, :value, :shell_url, :files_url)
```

* for a `Path` the shell_url and files_url could be determined along with the path string and the attribute name

**Comment by ericfranz** [comment]
Using a table for attributes with 0 cell padding and bootstrap striped:

<img width="1147" alt="screen shot 2017-04-12 at 5 59 54 pm" src="https://cloud.githubusercontent.com/assets/512333/24981327/42d767a8-1faa-11e7-8e83-cd6038c6efce.png">

Using a table for attributes with the bootstrap condensed style:

<img width="1161" alt="screen shot 2017-04-12 at 6 01 21 pm" src="https://cloud.githubusercontent.com/assets/512333/24981333/485b6c1a-1faa-11e7-8f27-869cfaf1eb76.png">

In the table header I did this: `<td class="col-md-2">`

I don't think its terrible to have the unused space on the right and paths can have the buttons to open things to the right, similar to how default Rails list views are.

**Comment by brianmcmichael** [comment]
Resolved at https://github.com/OSC/ood-activejobs/pull/108
