### ISSUE TITLE
Memory conversion is not correct

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#109]
For a memory value of `556592` Active Jobs displays `556.49 MB`. It is doing division by `1000` instead of `1024` which RAM typically uses.

**Comment by brianmcmichael** [comment]
The [filesize](https://github.com/dominikh/filesize) gem formats based on the string. The first example is what torque provides. To get a division by 1024 the filesize gem would expect a tag of `KiB`.

```
irb(main):001:0> Filesize.from("556592kb").pretty
=> "556.59 MB"
irb(main):002:0> Filesize.from("556592 kb").pretty
=> "556.59 MB"
irb(main):003:0> Filesize.from("556592 KiB").pretty
=> "543.55 MiB"
```

**Comment by ericfranz** [comment]
Maybe we should just drop the gem and do our own display.

**Comment by brianmcmichael** [comment]
That shouldn't be a problem. I think the gem was used more in the old view. Now it looks like it's only used at

```
app/models/jobstatusdata.rb:    attributes.push Attribute.new "Memory", Filesize.from(mem).pretty
app/models/jobstatusdata.rb:    attributes.push Attribute.new "Virtual Memory", Filesize.from(vmem).pretty
```

Probably best to just show the adapter output here.

**Comment by nickjer** [comment]
Just a note, the `"556592kb"` provided by Torque I believe is equivalent to "1024 * 556592 bytes"

**Comment by ericfranz** [comment]
1f7c0c84dcea25d5a863638114cee321031e58d1
