### ISSUE TITLE
Add cluster-specific filters by default

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#116]
A suggestion by Martin Cuma was adding to the current "My Jobs" and "All Jobs" filtering the ability to further break it down to cluster-specific views as well.

Maybe buttons are not the ideal way of going about this, so if we add this feature a design proposal may be necessary.

Original text:

>In either case, for the multi-cluster environment like ours, it's be good 
if the "Jobs" menu in the Dashboard showed each cluster separately, 
perhaps both for All Jobs and My Jobs. Or, even better, for My Jobs scan 
all the clusters.
>
>I figure we can do this ourselves with the Custom Filter as you describe 
here:
https://github.com/OSC/ood-activejobs
but, not knowing anything about the OOD internal data structures, I don't 
know how to modify the example for something like that.

**Comment by nickjer** [comment]
Two other reasons for cluster-only views:

- there is a cluster named "ash" but a lot of users have job names called "bash"
- if there are a lot of clusters, calling `qstat` on all of them can be time consuming making the "All Jobs" load time unacceptable

**Comment by ericfranz** [comment]
A wrinkle in that is if there is only one cluster we wouldn't show this second list of filter options.

Also for clusters, maybe we consider a button dropdown (or just a normal dropdown):

<img width="169" alt="screen shot 2017-04-27 at 10 57 01 am" src="https://cloud.githubusercontent.com/assets/512333/25489655/788d0fee-2b38-11e7-80b4-4113e193f22f.png">
<img width="171" alt="screen shot 2017-04-27 at 10 57 22 am" src="https://cloud.githubusercontent.com/assets/512333/25489654/788bc300-2b38-11e7-9f71-75db7cf9059a.png">

**Comment by nickjer** [comment]
You could also replicate @ericfranz's idea for the "My Jobs" and "All Jobs" buttons.
