### ISSUE TITLE
Add extended data for LSF

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-activejobs#123]
Create a method to build an extended_data output on LSF systems.

Steps: 

* Add an `extended_data_lsf` method to the [Jobstatusdata](https://github.com/OSC/ood-activejobs/blob/master/app/models/jobstatusdata.rb) model, patterned after the torque and slurm methods.
* Add an `elseif` to the initializer logic like `elsif OODClusters[cluster].job_config[:adapter] == "lsf"` and calls the lsf method.

**Comment by ericfranz** [comment]
For this, don't add any code to actually parse these values in the "native" hash into any Ruby objects. Just display the string values as is.

Example: https://github.com/OSC/ood_core/blob/e1cd24086659d95c390baab16b399367775bc441/spec/job/adapters/lsf/batch_spec.rb#L65-L79

Everything but `id`, `user`, `queue`, `name` would be useful, as the original string values from the bjobs command are not available via the table.
