### ISSUE TITLE
Display the actual host name(s) that a job is running on.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-activejobs#141]
Was explaining to a user the difference between quick-batch and ruby-batch and the question came up about which node the the quick-batch job was running on.

I should display the name of the physical node a job is running on, currently I do this via the ganglia displays, but for clusters like quick and at remote sites, this option is not available.

**Comment by nickjer** [comment]
I like this feature as it can be useful for all the external sites that don't use Ganglia. I would suggest adding this as an Ingest item on Asana to be brought up for discussion.
