### ISSUE TITLE
SECURITY: Update paperclip to latest version

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-activejobs#153]
Github warns that there's a security issue with the current version of `paperclip` gem. This should be updated to a secure version.

![paperclipvuln](https://user-images.githubusercontent.com/2374718/35397787-5bc2d5a8-01be-11e8-917f-b0c400424cb5.png)

**Comment by ericfranz** [comment]
Remove paperclip as it is not used by activejobs.
