### ISSUE TITLE
Active jobs raises error if cached default cluster doesn't exist

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-activejobs#170]
The top right dropdown shows "All Clusters" or an entry for each cluster. When you select options, the value is stored in local storage with the key "jobcluster". If you open "Storage" tab in Firefox developer tools, and change jobcluster to oakley, then access https://ondemand.osc.edu/pun/sys/activejobs directly you will see an error:

![screen 2018-12-20 at 10 28 08 am](https://user-images.githubusercontent.com/512333/50293819-72affe80-0442-11e9-8cbe-fc64361a8d87.png)

This is the type of error you would see if a cluster is specified here that used to exist, but then was recently decomissioned and then does not; any user who had this set last would now see the cryptic error above.

In this case we should choose the next valid option in the dropdown and update the local storage. We should also fix the error reporting so it contains more helpful information (such as the above could have stated "There was an error getting data from the remote server for oakley." which would have been better than what it does right now.

**Comment by laser505t** [comment]
Fixed in [c7096b9](https://github.com/OSC/ood-activejobs/commit/c7096b9475124e0cd1ce94d6a96f0f74a0c0c0c8) according to @MorganRodgers. See #171.
