### ISSUE TITLE
Direct link to job statistics

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#45]
Provide a direct link that can be shared between users that shows them the view for a single job.

**Comment by nickjer** [comment]
This issue was brought up again by Shameema after a workshop she recently gave.

**Comment by nickjer** [comment]
Similar to a show view that a Rails resource provides. Basically it is a single page that shows the full details of a job (similar to what we show when you expand the row in the table) but in a single HTML page.

**Comment by nickjer** [comment]
Adding @brianmcmichael and @ericfranz as participants.

**Comment by ericfranz** [comment]
Duplicate of #160
