### ISSUE TITLE
When showing details of a job, update job row

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-activejobs#68]
Clicking the progressive disclosure on a job shows its details after fetching the updated data from the server. After this fetch, the corresponding row information probably should also be updated. For example, one of my jobs just completed:

![screen shot 2017-01-18 at 4 04 27 pm](https://cloud.githubusercontent.com/assets/512333/22082958/e28f3f78-dd97-11e6-9e13-7076155eb549.png)

A side thought: React.js could be a consideration for this app, as it is a small app and React.js is a small library. Might be worth an experiment. Of course, having that work with datatables might be problematic.

**Comment by brianmcmichael** [comment]
Resolved by https://github.com/OSC/ood-activejobs/commit/24a174fc9cf7c1a0a49f965b701c62ac9601000a
