### ISSUE TITLE
Progressive display shows nothing when job has let the queue

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-activejobs#69]
The job changed to completed status temporarily so when I clicked progressive disclosure button it shows this:

![screen shot 2017-01-18 at 4 04 27 pm](https://cloud.githubusercontent.com/assets/512333/22083061/643c7716-dd98-11e6-863c-ec8c526e6b5f.png)

Then I close it and reopen it and I see this:

![screen shot 2017-01-18 at 4 08 52 pm](https://cloud.githubusercontent.com/assets/512333/22083073/6e32b3ac-dd98-11e6-9f18-22ab331866c6.png)

If nothing is available, at least it might be worth doing two things:

1. Change Status to Completed (related to #68)
2. Say "No job details avialable as has left the queue."

![screen shot 2017-01-18 at 4 15 05 pm](https://cloud.githubusercontent.com/assets/512333/22083286/56440538-dd99-11e6-846c-b4f343eade61.png)

Of course if and when the user refreshes the page this row will no longer display.

**Comment by brianmcmichael** [comment]
Commit #78 was merged.
