### ISSUE TITLE
Add OOD installation documentation and properly handle defaults

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-activejobs#76]
- [ ] 1. If Active Jobs is installed, but File Explorer is not installed, do we still display the "open results dir" in new window?
- [x] 2. Add New Install and Updating to a New Stable Version sections, including and following example of https://github.com/OSC/ood-dashboard and https://github.com/OSC/ood-fileexplorer#usage make sure to mention adding the cluster config that this app depends on with a TODO to link to the documentation that explains cluster configs. I'll add that if it is missing (at least a basic version).
- [x] 3. If no clusters config exists, does it crash? What happens?

**Comment by ericfranz** [comment]
@brianmcmichael after #72 and #77

**Comment by brianmcmichael** [comment]
1.) There doesn't appear to be any logic to handle this case. Similarly for shell.

3.) I haven't tested this yet, but bad things will happen.

**Comment by brianmcmichael** [comment]
For (1), Posted the question at https://github.com/OSC/ood_appkit/issues/35 about Files and Shell. I'm not sure yet if OodAppkit provides a way to detect the availability of these dependent apps, it looks like it just defaults to a path. I can detect by checking the folder paths in the app, but it may make more sense to move this to OodAppkit. If it's there, the documentation may need to be updated.

For (3), I added a `rescue` block at https://github.com/OSC/ood-activejobs/commit/7752e8a7b94cc4bbec9fa1cfd932d625874f855b for the case when `OodAppkit.clusters` fails. The app doesn't crash when OODClusters is an empty hash. I'm not sure how OodAppkit itself handles a missing cluster config.

For (2), The New Install instructions have been merged to master. I'll add the "updating" guide. We already mention that File Explorer and Shell are required. Once I get a better understanding of (1) I can hide file and shell options if necessary and they won't need to be hard requirements.

**Comment by ericfranz** [comment]
>1. If Active Jobs is installed, but File Explorer is not installed, do we still display the "open results dir" in new window?

Since we document on the README that this app assumes File Explorer is installed, and the rest of the concerns have been addressed, I'm closing this issue as complete.
