### ISSUE TITLE
Add queue and time used columns

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-activejobs#89]
When I do qstat I see 2 columns that we don't show on active jobs:

```
efranz@owens-login04:~$ qstat 663152.owens-batch.ten.osc.edu
Job ID                    Name             User            Time Use S Queue
------------------------- ---------------- --------------- -------- - -----
663152.owens-batch.ten.osc.ed spark-stati      soottikkal      00:17:38 C parallel
```

Might be useful, if available on info, to show `time used / walltime requested`.

**Comment by brianmcmichael** [comment]
This was added at https://github.com/OSC/ood-activejobs/commit/8482aaf161f20ada14597443a10f2fa4f9603318

**Comment by brianmcmichael** [comment]
Change merged at https://github.com/OSC/ood-activejobs/pull/88
