### ISSUE TITLE
Consider minifying json response data keys.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-activejobs#91]
A json response currently looks like:

```
[{"pbsid":"8724294.oak-batch.osc.edu","jobname":"parallel_fluent","username":"osu0842","account":"PAS0228","status":"queued_held","cluster":"oakley","extended_available":true}]
```

By encoding these keys to a single char we can decrease the size of the response by 30% and speed up the wait while jobs download and parse, we could probably get a better than 30% speed improvement when you compound clientside processing. This would be a valuable UX improvement because there is a longish wait time when requesting "All Jobs"

The big downfall is that the code would be a little more difficult to read, which could be overcome by appropriate inline documentation and renaming them back to more user-friendly options once they arrive at client-side.

**Comment by ericfranz** [comment]
When using the Active Jobs app from Chrome, the request headers sent include:

```
Accept-Encoding:gzip, deflate, sdch, br
```

and the response headers include:

```
Content-Encoding:gzip
```

I don't think we will beat gzip.

**Comment by brianmcmichael** [comment]
You are right. The raw text is currently at `834 KB`, but Chome says the download size is `37.2 KB`, so it appears that the magic is already happening. Closing.

**Comment by ericfranz** [comment]
FWIW on the "Timing" tab on the ajax request in Chrome dev tools I see this:

![screen shot 2017-03-29 at 3 37 12 pm](https://cloud.githubusercontent.com/assets/512333/24472955/a044ce46-1495-11e7-9a7d-9c5e7152cac8.png)

1. Time to First Byte is 2.20 seconds
2. Content Download time of gzipped data is 14.28ms

So the question there would be, where in the request is the most of the 2.20 seconds spent? https://www.skylight.io/ for Rails apps is amazing, but there are plenty of profiling options available.

**Comment by brianmcmichael** [comment]
Ok, the ajax request from datatables isn't fired until after `$(document).ready()`, so there's a good chance we're waiting for all of the other page components to load.

**Comment by brianmcmichael** [comment]
Nevermind, TTFB means we're waiting on the serverside. Got it.

**Comment by ericfranz** [comment]
Actually not sure about that.

See:

![screen shot 2017-03-29 at 4 02 14 pm](https://cloud.githubusercontent.com/assets/512333/24473999/385d7cca-1499-11e7-9f34-9d0ad505f678.png)

we have 2 requests we respond slowly to:

1. the initial request for the app root /pun/sys/activejobs

![screen shot 2017-03-29 at 4 04 12 pm](https://cloud.githubusercontent.com/assets/512333/24474108/9045df54-1499-11e7-808b-4f87d43e5608.png)

2. the ajax request for json qstat

![screen shot 2017-03-29 at 4 04 19 pm](https://cloud.githubusercontent.com/assets/512333/24474116/97923d70-1499-11e7-8997-b35823925d2c.png)

The rest of the requests total take half a second.
