### ISSUE TITLE
Intermittent issues with OSC custom filter disappearing

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-activejobs#92]
In the OSC implementation, a custom filter is added at initialization.

https://github.com/OSC/ood-activejobs/blob/master/config/initializers/filter.rb.osc

I have noticed that occasionally this filter disappears when rendering the view, however, and only displays the two defaults. For some reason the initialized class doesn't appear to always "stick".

I can not reliably reproduce this error. On some reloads it uses the proper `Filter` class, and sometimes it uses the default class.

I think my best option here is to define a static variable and assign `Filter.list` to that in the initializer and call that instead.

**Comment by ericfranz** [comment]
Are you staying that the view only shows 2 tabs instead of three, or are you saying that the filter that is loaded when the page loads is incorrect?

I don't understand this:

>On some reloads it uses the proper Filter class, and sometimes it uses the default class.

>I have noticed that occasionally this filter disappears when rendering the view, however, and only displays the two defaults.

Its important to understand the defect and have a reliable set of steps to reproduce before trying to fix it.

**Comment by brianmcmichael** [comment]
2 tabs instead of three. The custom one specified in the initializer is missing. Waiting and reloading later can correct the issue.

As mentioned, I can not reliably reproduce this error yes, but I have observed it on several occasions.

**Comment by brianmcmichael** [comment]
This may be caused by the fact that our custom filter is defined in an initializer. I have my suspicions that if I make changes in development to a model, rails may reload all of the models and skip the `tap` method. 

If that's the case, this issue should not appear in production, but I'm still trying to think of a way to test it reliably.

**Comment by brianmcmichael** [comment]
Confirmed, this happens after modifying a Model class. I'm assuming Rails reloads all models when one changes, and reloading the `Filter` class without passing through the initializer would cause it to reset.

It may be a good idea to somehow encapsulate that block of code in the initializer to a variable and have it explicitly `tap`ped in to the model when it load.

**Comment by brianmcmichael** [comment]
This problem only appears to affect development. Updating a model skips the initializer. Models will not be altered on the fly during production.
