### ISSUE TITLE
Clicking a new tab should not depend on local storage (or cookies) to work

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-activejobs#95]
The current functionality is when we click a new tab:

1. user clicks tab 
2. set clicked the tab id to local storage
3. reload the page
4. read the tab id from local storage and make this the active filter

Instead it should be

1. user clicks tab => this should probably be a link to the same page with a query param set to the filter id (alternatively use a click handler to read the id or data attribute or href)
2. browser goes to requested page
3. since query param is set, make this the active filter AND write this to local storage (set the query param via ruby which should be easier than parsing it using javascript) https://github.com/OSC/ood-activejobs/blob/aed863e44b54599cbfff6775f1a5d7594ac0045c/app/views/pages/index.html.erb#L28 (so query param? set active filter and write to localStorage, otherwise, use `localStorage.getItem("jobfilter") || "<%= Filter.default_id %>"`

**Comment by ericfranz** [comment]
But since we probably want to support auto-updates in the future, maybe tab click events should be handled by a click event handler that sends the user to the proper location.

**Comment by brianmcmichael** [comment]
Done at https://github.com/OSC/ood-activejobs/commit/79f1b127d47e448b143d03a04f136f510aac1ad4
