### ISSUE TITLE
Completed jobs cause error with stack trace

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#97]
How to reproduce:

1. Load Active Jobs
2. Find a "Running" job
3. Wait for that job to finish
4. Don't refresh the page, but instead click the extended details dropdown button for the use-to-be "Running" job

You get this...

![image](https://cloud.githubusercontent.com/assets/4260509/24803365/ff8c054c-1b78-11e7-87c7-ccaa0afda569.png)

**Comment by brianmcmichael** [comment]
This is because the slurm adapter is reporting something other than `PBS::UnkjobidError` see:

https://github.com/OSC/ood-activejobs/blob/ood_core/app/controllers/pages_controller.rb#L54-L57

I'll have to update this rescue to look for whatever error OodCore throws when a job is unknown.

**Comment by nickjer** [comment]
You won't ever get `PBS` errors if you are using `ood_core`. All errors will be `OodCore::JobAdapterError` now.

**Comment by nickjer** [comment]
Also, I am not sure how I feel about rescuing every possible exception raised here:

```ruby
    rescue => e
      { name: pbsid, error: "No job details available." + e.backtrace.to_s}
```

Sometimes raising a 5xx is fine. Especially if it is something unrelated to a `OodCore::JobAdapterError`.

**Comment by brianmcmichael** [comment]
Ideally the user will never see this block of code. This is here for us to debug unexpected behavior, like when the underlying API changes.

**Comment by brianmcmichael** [comment]
Fix applied at https://github.com/OSC/ood-activejobs/commit/bd5f7802df79afcc1a220b3bae1537b3c960db7e
