### ISSUE TITLE
Bad submit args on Slurm

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-activejobs#99]
I submitted a job from command line as:

```sh
echo -e '#!/bin/bash\necho "hello world"' | sbatch -M ember -H --parsable
```

and my view looks like this:

![image](https://cloud.githubusercontent.com/assets/4260509/24804218/bd6af58a-1b7b-11e7-8a13-91233ef2cd48.png)

Notice that "Submit Args" is `(null)`. Is this something we expect?

**Comment by brianmcmichael** [comment]
This is Slurm's response.

It's using `info.native[:command]` verbatim on slurm systems.

**Comment by nickjer** [comment]
Ok, so this is the native `:command` attribute. This is not going to return the submit args, but will only return the command the batch job will run. Since I submitted the job through `STDIN`, it doesn't have a direct command to call.

This should be discussed in #98 for possible removal from the view.

**Comment by brianmcmichael** [comment]
Alternatively, we could use a more general name. There is still useful data reported here for other jobs that I am wary about removing.
